from django.db import models

# Create your models here.
class students(models.Model):
    pin_number = models.CharField(max_length=100, primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)
    year = models.IntegerField()
    
    first_year_101_UT1 = models.BigIntegerField(null=True, blank=True)
    first_year_102_UT1 = models.BigIntegerField(null=True, blank=True)
    first_year_103_UT1 = models.BigIntegerField(null=True, blank=True)
    first_year_104_UT1 = models.BigIntegerField(null=True, blank=True)
    first_year_105_UT1 = models.BigIntegerField(null=True, blank=True)
    first_year_106_UT1 = models.BigIntegerField(null=True, blank=True)
    first_year_101_UT2 = models.BigIntegerField(null=True, blank=True)
    first_year_102_UT2 = models.BigIntegerField(null=True, blank=True)
    first_year_103_UT2 = models.BigIntegerField(null=True, blank=True)
    first_year_104_UT2 = models.BigIntegerField(null=True, blank=True)
    first_year_105_UT2 = models.BigIntegerField(null=True, blank=True)
    first_year_106_UT2 = models.BigIntegerField(null=True, blank=True)
    first_year_107_P = models.BigIntegerField(null=True, blank=True)
    first_year_108_P = models.BigIntegerField(null=True, blank=True)
    first_year_109_P = models.BigIntegerField(null=True, blank=True)
    first_year_110_P = models.BigIntegerField(null=True, blank=True)
    first_year_101_F = models.BigIntegerField(null=True, blank=True)
    first_year_102_F = models.BigIntegerField(null=True, blank=True)
    first_year_103_F = models.BigIntegerField(null=True, blank=True)
    first_year_104_F = models.BigIntegerField(null=True, blank=True)
    first_year_105_F = models.BigIntegerField(null=True, blank=True)
    first_year_106_F = models.BigIntegerField(null=True, blank=True)
    first_year_107_F = models.BigIntegerField(null=True, blank=True)
    first_year_108_F = models.BigIntegerField(null=True, blank=True)
    first_year_109_F = models.BigIntegerField(null=True, blank=True)
    first_year_110_F = models.BigIntegerField(null=True, blank=True)

    second_year_301_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_302_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_303_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_304_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_305_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_301_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_302_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_303_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_304_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_305_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_306_P = models.BigIntegerField(null=True, blank=True)
    second_year_307_P = models.BigIntegerField(null=True, blank=True)
    second_year_308_P = models.BigIntegerField(null=True, blank=True)
    second_year_309_P = models.BigIntegerField(null=True, blank=True)
    second_year_301_F = models.BigIntegerField(null=True, blank=True)
    second_year_302_F = models.BigIntegerField(null=True, blank=True)
    second_year_303_F = models.BigIntegerField(null=True, blank=True)
    second_year_304_F = models.BigIntegerField(null=True, blank=True)
    second_year_305_F = models.BigIntegerField(null=True, blank=True)
    second_year_306_F = models.BigIntegerField(null=True, blank=True)
    second_year_307_F = models.BigIntegerField(null=True, blank=True)
    second_year_308_F = models.BigIntegerField(null=True, blank=True)
    second_year_309_F = models.BigIntegerField(null=True, blank=True)

    second_year_401_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_402_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_403_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_404_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_405_UT1 = models.BigIntegerField(null=True, blank=True)
    second_year_401_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_402_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_403_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_404_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_405_UT2 = models.BigIntegerField(null=True, blank=True)
    second_year_406_P = models.BigIntegerField(null=True, blank=True)
    second_year_407_P = models.BigIntegerField(null=True, blank=True)
    second_year_408_P = models.BigIntegerField(null=True, blank=True)
    second_year_409_P = models.BigIntegerField(null=True, blank=True)
    second_year_401_F = models.BigIntegerField(null=True, blank=True)
    second_year_402_F = models.BigIntegerField(null=True, blank=True)
    second_year_403_F = models.BigIntegerField(null=True, blank=True)
    second_year_404_F = models.BigIntegerField(null=True, blank=True)
    second_year_405_F = models.BigIntegerField(null=True, blank=True)
    second_year_406_F = models.BigIntegerField(null=True, blank=True)
    second_year_407_F = models.BigIntegerField(null=True, blank=True)
    second_year_408_F = models.BigIntegerField(null=True, blank=True)
    second_year_409_F = models.BigIntegerField(null=True, blank=True)


    third_year_501_UT1 = models.BigIntegerField(null=True, blank=True)
    third_year_502_UT1 = models.BigIntegerField(null=True, blank=True)
    third_year_503_UT1 = models.BigIntegerField(null=True, blank=True)
    third_year_504_UT1 = models.BigIntegerField(null=True, blank=True)
    third_year_505_UT1 = models.BigIntegerField(null=True, blank=True)
    third_year_501_UT2 = models.BigIntegerField(null=True, blank=True)
    third_year_502_UT2 = models.BigIntegerField(null=True, blank=True)
    third_year_503_UT2 = models.BigIntegerField(null=True, blank=True)
    third_year_504_UT2 = models.BigIntegerField(null=True, blank=True)
    third_year_505_UT2 = models.BigIntegerField(null=True, blank=True)
    third_year_506_P = models.BigIntegerField(null=True, blank=True)
    third_year_507_P = models.BigIntegerField(null=True, blank=True)
    third_year_508_P = models.BigIntegerField(null=True, blank=True)
    third_year_509_P = models.BigIntegerField(null=True, blank=True)
    third_year_501_F = models.BigIntegerField(null=True, blank=True)
    third_year_502_F = models.BigIntegerField(null=True, blank=True)
    third_year_503_F = models.BigIntegerField(null=True, blank=True)
    third_year_504_F = models.BigIntegerField(null=True, blank=True)
    third_year_505_F = models.BigIntegerField(null=True, blank=True)
    third_year_506_F = models.BigIntegerField(null=True, blank=True)
    third_year_507_F = models.BigIntegerField(null=True, blank=True)
    third_year_508_F = models.BigIntegerField(null=True, blank=True)
    third_year_509_F = models.BigIntegerField(null=True, blank=True)
    
    
    third_year_601_F = models.BigIntegerField(null=True, blank=True)
  

 